### ISSUE TITLE
support scoping with pipe |

### ISSUE THREAD

**Issue by agileapplications** [agileapplications/i18n_screwdriver#2]
_("Account|Vorname").should be("Vorname")
_("User|Vorname").should be("Vorname")

_("Account|Vorname").translation_key.should be("Account|Vorname")
_("User|Vorname").translation_key.should be("User|Vorname")

That supports different translations in foreign languages for the same word.

**Comment by agileapplications** [comment]
@gucki Can you also do this one? Would be great.

**Comment by gucki** [comment]
@agileapplications I just checked and it seems I already implemented it back in 2014 ;-). Please check and reopen if it's not working as desired.
