### ISSUE TITLE
Default language not set correctly

### ISSUE THREAD

**Issue by manubo** [agileapplications/i18n_screwdriver#5]
Version 8 of i18n_screwdriver does not pick up the _I18n.default_langue = :de_ we have set in _initializers/locale.rb_. The task _i18n:update_ uses _:en_ as the default language. Switching back to version 7.2 works again. I did not try the other versions after 7.3.

**Comment by gucki** [comment]
@manubo You have to put it into application.rb directly. The reason is the i18n screwdriver rake task doesn't preload the complete rails env anymore.

**Comment by manubo** [comment]
@gucki Yes, that works, thanks.
