### ISSUE TITLE
 too many urls specified (1 <> 0)

### ISSUE THREAD

**Issue by agileapplications** [agileapplications/i18n_screwdriver#6]
I think it's crappy that this leads to an exception. We should just ignore this:

- less urls specified: just write the link's text without a url
- to many urls: just ignore them

**Comment by gucki** [comment]
Why is it bad? If the translations are correct, everything should work? If they are broken (a translator messed them up), isn't it good to be informed about it?

**Comment by agileapplications** [comment]
Problem is that the exception is completely disproportional in this situation. An exception on the whole page because a link is missing???

I mean lets keep the exception but fail silently in PRODUCTION.

**Comment by gucki** [comment]
This has been resolved with https://github.com/agileapplications/i18n_screwdriver/commit/3ea9a180238681889dd2bf2b9d3eba2d5e8cd501
