### ISSUE TITLE
Ignore directories and node_modules folder

### ISSUE THREAD

**Issue by manubo** [agileapplications/i18n_screwdriver#7]
i18n:update raises an exception if a folder exists that ends with `.(js|coffee|hamlc|ejs|erb)`. Such a file existed within my node_modules folder. Appart from that problem, I think it would be reasonable to ignore the node_modules folder altogether.

**Comment by gucki** [comment]
https://github.com/agileapplications/i18n_screwdriver/pull/8 fixes part of the problem

**Comment by manubo** [comment]
@gucki Yes, but not as long as it is not merged ;-)

**Comment by agileapplications** [comment]
@manubo I released it -> 9.1
