### ISSUE TITLE
I18n.screw does not support ECMA Script template literals

### ISSUE THREAD

**Issue by manubo** [agileapplications/i18n_screwdriver#9]
For example, the following translation is not catched by the updater:

```
I18n.screw(`Assessment "${title}" saved`)
```

**Comment by agileapplications** [comment]
@manubo Who writes ECMA Script? ;-)

**Comment by agileapplications** [comment]
I should rename the project: "i18n_screwdriver_on_caffeine" ;-)

**Comment by agileapplications** [comment]
@manubo Pull-Request? Should be in https://github.com/agileapplications/i18n_screwdriver/blob/master/lib/i18n_screwdriver.rb#L39

**Comment by manubo** [comment]
@agileapplications Pull Request submitted, thanks for the hint!

**Comment by agileapplications** [comment]
@manubo 9.2 released, thx!
